### ISSUE TITLE
Error on disbursement webhook object with to_json

### ISSUE THREAD

**Issue by getupstream** [braintree/braintree_ruby#140]
### General information

* SDK/Library version: 
* Environment: test
* Language, language version, and OS: ruby, 2.3.4, Mac OSX

### Issue description

I get an error when I attempt to transform a disbursement webhook object into json. This works for other types like disputes. 

```ruby
sample_notification = Braintree::WebhookTesting.sample_notification(
  Braintree::WebhookNotification::Kind::Disbursement,
  SecureRandom.uuid
)

webhook_notification = Braintree::WebhookNotification.parse(
  sample_notification[:bt_signature],
  sample_notification[:bt_payload]
)

webhook_notification.disbursement.to_json
IOError: not opened for reading
	from /Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/core_ext/object/json.rb:130:in `each'
	from /Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/core_ext/object/json.rb:130:in `to_a'
	from /Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/core_ext/object/json.rb:130:in `as_json'
	from /Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/core_ext/object/json.rb:161:in `block in as_json'
	from /Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/core_ext/object/json.rb:161:in `each'
	from /Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/core_ext/object/json.rb:161:in `map'
	from /Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/core_ext/object/json.rb:161:in `as_json'
	from /Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/core_ext/object/json.rb:52:in `as_json'
	from /Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/core_ext/object/json.rb:161:in `block in as_json'
	from /Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/core_ext/object/json.rb:161:in `each'
	from /Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/core_ext/object/json.rb:161:in `map'
	from /Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/core_ext/object/json.rb:161:in `as_json'
	from /Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/core_ext/object/json.rb:52:in `as_json'
	from /Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/core_ext/object/json.rb:161:in `block in as_json'
	from /Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/core_ext/object/json.rb:161:in `each'
	from /Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/core_ext/object/json.rb:161:in `map'
... 7 levels...
	from /Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/core_ext/object/json.rb:161:in `block in as_json'
	from /Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/core_ext/object/json.rb:161:in `each'
	from /Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/core_ext/object/json.rb:161:in `map'
	from /Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/core_ext/object/json.rb:161:in `as_json'
	from /Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/core_ext/object/json.rb:52:in `as_json'
	from /Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/json/encoding.rb:33:in `encode'
	from /Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/json/encoding.rb:20:in `encode'
	from /Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/core_ext/object/json.rb:37:in `to_json'
	from (irb):11
	from /Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-5.0.2/lib/rails/commands/console.rb:65:in `start'
	from /Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-5.0.2/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/username/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'```

**Comment by getupstream** [comment]
Happy to provide more context if need. 

As to why this is important. This is stopping us from easily passing the disbursement webhook to a backend worker.

**Comment by khpatel4991** [comment]
What If I need to persist the response object for query use as json field in my psql table?

**Comment by sdcoffey** [comment]
Hey @getupstream and @khpatel4991,

For either of these scenarios, I would recommend passing the raw payload and signature to either your backend worker or to postgres, and parsing them at the time that you need them. While I can't say for sure why `to_json` doesn't throw an exception for a dispute object, `to_json` is not a method or functionality that we support on any of our response objects. Let me know if this is a viable solution for you both.

**Comment by sdcoffey** [comment]
Hey @getupstream and @khpatel4991,

I'm closing this issue due to inactivity. Please comment here if you'd like to continue this discussion and I'll reopen the issue.

**Comment by michelson** [comment]
We have got this error today on transactions .to_json in rails 4.1.14

**Comment by michelson** [comment]
please reopen this

**Comment by michelson** [comment]
I've "handled" this by using `.instance_values` instead of `.as_json` , but the bug still there

**Comment by michelson** [comment]
this bug is still happening 👎

**Comment by crookedneighbor** [comment]
@michelson Does this suggestion not work for you? https://github.com/braintree/braintree_ruby/issues/140#issuecomment-298396427

**Comment by crookedneighbor** [comment]
Going to close this as I haven't received a response from @michelson about storing the raw payload instead.
